config/routes.rb
Rails.application.routes.draw do
 
  devise_for :users
  resources :projects do
    resources :tasks do
      member do
        patch :complete
      end
      put :sort, on: :collection
    end
  end
  
  resources :tasks
  root 'projects#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	belongs_to :user
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  validates_presence_of :name

  default_scope { order("priority ASC") }
  def completed?
  	!completed_at.blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :set_project, only: [:show, :edit, :update, :destroy]
  respond_to :html, :js
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
    @project = Project.new

  end   

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.create(project_params)
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def edit

  end
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'project was successfully updated.' }
        format.json { respond_with_bip(@project) }
      else
        format.html { render :edit }
        format.json { respond_with_bip(@project) }
      end
    end
  end
  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_with @project
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	respond_to :html, :js
	before_action :set_task, except: [:create]

	def create
	    @project = Project.find(params[:project_id])
	    @task = @project.tasks.create(task_params)
	    @task.save

	    respond_to do |format|
	  	    format.js
	    end
	end
	  
 	def sort
    	params[:order].each do |key,value|
      		Task.find(value[:id]).update_attribute(:priority,value[:position])
    	end
    render :nothing => true
  	end

	def destroy
		@task = Task.find(params[:id])
	    @task.destroy
	    respond_to do |format|
	    	format.js
		end
	end

	def update
		@task = Task.find(params[:id])
	    respond_to do |format|
	      	if @task.update(task_params)
		        format.html { redirect_to @task, notice: 'task was successfully updated.' }
		        format.json { respond_with_bip(@task) }
	     	else
		        format.html { render :edit }
		        format.json { respond_with_bip(@task) }
	     	end
	    end
	end

	def edit
	    @task = Task.find(params[:id])
	end

	def complete
		@task.update_attribute(:completed_at, Time.now)
		redirect_to root_path
	end
	  
	private

	def set_task
	  	@task = Task.find(params[:id])
	end
	
	def task_params
		params.require(:task).permit!
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

  <title>Kirill</title>
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
</head>

<body>

<% if current_user %>
	<span>Welcome, <%= current_user.email %></span>
	<%= link_to destroy_user_session_path, :method => :delete, class: "btn btn-danger" do %>
    <i class="fa fa-sign-out"></i>
  <% end %>    
<% else %>
	<%= link_to new_user_registration_path, class: "btn btn-danger" do %>
    <i class="fa fa-registered"></i>
  <% end %>
	<%= link_to new_user_session_path, class: "btn btn-danger" do %>
    <i class="fa fa-sign-in"></i>
  <% end %>
<% end %>

<h1>PROJECTS</h1>

<%= yield %>

</body>

</html>

app/views/projects/_form.html.erb
<%= form_for(@project, :remote => true) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
      <%= f.text_field :name %><%= f.submit "Create project", class: 'btn btn-primary' %>
  </div> 
  
<% end %>

app/views/projects/_headerproject.html.erb
    <div id="re<%=project.id%>" style="outline:2px solid #000; width:500px; margin:auto; background-color:#fff" > 

        <div style="background-color:#525; color:red;height:35px;"><%= best_in_place project, :name, as: :input, activator: "#edit-project-name-#{project.id}" %>

        <%= link_to  project, style:"float:right;", class: "btn btn-danger", remote: true, method: :delete do %>
            <i class="fa fa-trash-o"></i>
        <% end %>
        <%= link_to "#", class: 'btn btn-primary', id: "edit-project-name-#{project.id}", style:"float:right;" do %>
            <i class="fa fa-pencil"></i>
        <% end %>
        
        <br>
        </div>

        <%= form_for([project, Task.new], :remote => true) do |f| %>  

        <div>
        
        <br>

        <%= f.text_field :name %><%= f.submit "Create task", class: 'btn btn-success' %>

        </div>

        <div class="actions" >

        <% end %>

        <ul class="sortable" id="task<%=project.id%>" style="padding:0px;">

        <% project.tasks.each do |task| %>

            <%= render 'tasks/task', :task => task %>

        <% end %>

        </ul>

        </div>

    </div>
    

    

app/views/projects/create.js.erb
$("<%= escape_javascript(render('headerproject', :project => @project)) %>").fadeIn(500).appendTo('#conteiner');
$('form input[type=text]').val(' ');
$('form textarea').val(' ');


$(document).ready(function() {
  $(".best_in_place").best_in_place();
});

app/views/projects/destroy.js.erb
$("<%= j (render('headerproject', :project => @project)) %>"); 
$("<%= "#re#{@project.id}" %>").hide();
 

app/views/projects/edit.html.erb
<h1>Editing Todolist</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<div id="conteiner">

	<% if user_signed_in? %>

		<% current_user.projects.each do |project| %> 

		<div id="re<%=project.id %>" style="margin-bottom:30px">

			<%= render 'headerproject', :project => project %>

		</div>

	<% end %>

</div>

<%= render 'form' %>

<% end %>

<div>

<a href="https://github.com/kirill8210/kirill">GitHub</a>

</div>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task, :remote => true) do |f| %>

<div class="field">

	<%= f.label :name %><br>
	<%= f.text_field :name %>

</div>

<div class="actions">

	<%= f.submit %>

</div>

<% end %>

app/views/tasks/_task.html.erb
<li id="re<%=task.id%>" data-id="<%=task.id%>" style="background-color:#fff;list-style:none;padding:25px;">

<% if task.completed? %>

	<i class="fa fa-check-square-o" class="btn btn-success" style="float:left;margin:20px;"></i>

	<b><%= best_in_place task, :name, as: :input, activator: "#edit-task-name-#{task.id}" , style:"width:250px;padding:10px;" %></b>

	<%= link_to task, class: "btn btn-danger", style:"float:right;margin:10px;", :remote => true, method: :delete do %>
	<i class="fa fa-trash-o"></i>
	<% end %>
	<br>

<% else %>

	<%= link_to complete_project_task_path(task.project, task), style:"float:left;margin:10px;", class: "btn btn-success", method: :patch do %>
	<i class="fa fa-square-o"></i>
	<% end %>

	<%= best_in_place task, :name, as: :input, activator: "#edit-task-name-#{task.id}" , style:"padding:10px;" %>
	<%= link_to task, class: "btn btn-danger", style:"float:right;margin:10px;", :remote => true, method: :delete do %>
	<i class="fa fa-trash-o"></i>
	<% end %>

	<%= link_to "#", class: 'btn btn-warning', style:"float:right;margin:10px;", id: "edit-task-name-#{task.id}" do %>
	<i class="fa fa-pencil"></i>
	<% end %>
	
	<br>

<% end %>

</li>

app/views/tasks/create.js.erb
$("<%= escape_javascript(render('tasks/task', :task => @task )) %>").fadeIn(1000).appendTo('#task<%="#{@project.id}"%>');
$('form input[type=text]').val(' ');
$('form textarea').val(' ');

$(document).ready(function() {
  $(".best_in_place").best_in_place();
});

app/views/tasks/destroy.js.erb
$("<%= j (render('tasks/task', :task => @task)) %>"); 
$("<%= "#re#{@task.id}" %>").hide();
 

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>